conversations:
   Jack:
      quester: Jack
      first: dialog_2_1,dialog_2_0,dialog_1_1
      NPC_options:
         dialog_1_1:
            text: |

                  Hallo %player%! Wie kann ich dir weiterhelfen?
            pointer: dialog_1_1_1
            conditions: '!finishedTag'
         dialog_1_2:
            text: |

                  Dein $professionName$ Level: %ph.mmocore_profession_$professionName$%
                  Du hast folgende Quests zur Auswahl:
            pointer: dialog_1_1_2,dialog_1_1_3,dialog_1_1_4,dialog_1_1_5,dialog_1_1_6,dialog_1_1_7,dialog_1_1_8,dialog_1_1_9,dialog_1_2_0
         dialog_1_3:
            text: |

                  Quest Level &a0 - 10&r
                  Belohnung: &a$rewardCurrencyAmountLevel1$ Gold | $rewardExperienceAmountLevel1$ Job Experience&r
                  Aufgabe: &6Töte $mobkillAmount_level0-10$ Monster der Stufe 1
         dialog_1_4:
            text: |

                  Quest Level &a10 - 30&r
                  Belohnung: &a$rewardCurrencyAmountLevel2$ Gold | $rewardExperienceAmountLevel2$ Job Experience
                  Aufgabe: &6Töte $mobkillAmount_level10-30$ Monster der Stufe 2 und $mobkillAmount2_level10-30$ Monster der Stufe 1
         dialog_1_5:
            text: |

                  Quest Level &a30 - 50&r
                  Belohnung: &a$rewardCurrencyAmountLevel3$ Gold | $rewardExperienceAmountLevel3$ Job Experience
                  Aufgabe: &6Töte $mobkillAmount_level30-50$ Monster der Stufe 3 und $mobkillAmount2_level30-50$ Monster der Stufe 2
         dialog_1_6:
            text: |

                  Quest Level &a50 - 80&r
                  Belohnung: &a$rewardCurrencyAmountLevel4$ Gold | $rewardExperienceAmountLevel4$ Job Experience
                  Aufgabe: &6Töte $mobkillAmount_level50-80$ Monster der Stufe 4 und $mobkillAmount2_level50-80$ Monster der Stufe 3
         dialog_1_7:
            text: |

                  Quest Level &a80 - 100&r
                  Belohnung: &a$rewardCurrencyAmountLevel5$ Gold | $rewardExperienceAmountLevel5$ Job Experience
                  Aufgabe: &6Töte $mobkillAmount_level80-100$ Monster der Stufe 5 und $mobkillAmount2_level80-100$ Monster der Stufe 4
         dialog_1_8:
            text: |

                  Bis bald!
         dialog_1_9:
            text: |

                  Viel Erfolg und komm wieder wenn du fertig bist!

                  &2Quest angenommen!&r
         dialog_2_0:
            text: |

                  &4Du hast bereits eine Quest am laufen!
                  &rSchließe die jetzige Quest ab, um andere Quests anzunehmen.
            conditions: 'startedTag,!finishedTag'
         dialog_2_1:
            text: |

                  Du hast es geschafft! Super gemacht.
                  Belohnung: 
            conditions: finishedTag
            events: rewardPlayer,resetQuest
      player_options:
         dialog_1_1_1:
            text: '&2Verfügbare Quests'
            pointer: dialog_1_2
         dialog_1_1_2:
            text: '&2Level 0 - 10 | Annehmen'
            pointer: dialog_1_3
            events: mobkillObjAdd,startedTagAdd,journalAdd1
         dialog_1_1_3:
            text: '&2Level 10 - 30 | Annehmen'
            conditions: level10orHigher
            pointer: dialog_1_4
            events: mobkillObjAdd1,mobkillObjAdd2,startedTagAdd,journalAdd2
         dialog_1_1_4:
            text: '&2Level 30 - 50 | Annehmen'
            conditions: level30orHigher
            pointer: dialog_1_5
            events: mobkillObjAdd2,mobkillObjAdd3,startedTagAdd,journalAdd3
         dialog_1_1_5:
            text: '&2Level 50 - 80 | Annehmen'
            conditions: level50orHigher
            pointer: dialog_1_6
            events: mobkillObjAdd3,mobkillObjAdd4,startedTagAdd,journalAdd4
         dialog_1_1_6:
            text: '&2Level 80 - 100 | Annehmen'
            conditions: level80orHigher
            pointer: dialog_1_7
            events: mobkillObjAdd4,mobkillObjAdd5,startedTagAdd,journalAdd5
         dialog_1_1_7:
            text: '&4Level 10 - 30 | Level zu niedrig'
            conditions: '!level10orHigher'
            pointer: dialog_1_2
         dialog_1_1_8:
            text: '&4Level 30 - 50 | Level zu niedrig'
            conditions: '!level30orHigher'
            pointer: dialog_1_2
         dialog_1_1_9:
            text: '&4Level 50 - 80 | Level zu niedrig'
            conditions: '!level50orHigher'
            pointer: dialog_1_2
         dialog_1_2_0:
            text: '&4Level 80 - 100 | Level zu niedrig'
            conditions: '!level80orHigher'
            pointer: dialog_1_2

events:
   mobkillObjAdd: objective start mobkillObj
   mobkillObjAdd1: objective start mobkillObj1
   mobkillObjAdd2: objective start mobkillObj2
   mobkillObjAdd3: objective start mobkillObj3
   mobkillObjAdd4: objective start mobkillObj4
   mobkillObjAdd5: objective start mobkillObj5
   startedTagAdd: tag add startedTag
   finishedLevel: run ^tag add finishedTag ^objective delete mobkillObj ^journal add step_6 ^journal update ^deletepoint mobkillsLevel conditions:hasEnoughKills
   finishedLevel1: run ^point tag 1 ^tag add finishedTag1 ^objective delete mobkillObj1 ^deletepoint mobkillsLevel1 conditions:hasEnoughKills1
   finishedLevel2: run ^point tag 1 ^tag add finishedTag2 ^objective delete mobkillObj2 ^deletepoint mobkillsLevel2 conditions:hasEnoughKills2
   finishedLevel4: run ^point tag 1 ^tag add finishedTag1 ^objective delete mobkillObj3 ^deletepoint mobkillsLevel3 conditions:hasEnoughKills3
   finishedLevel5: run ^point tag 1 ^tag add finishedTag2 ^objective delete mobkillObj4 ^deletepoint mobkillsLevel4 conditions:hasEnoughKills4
   finishedLevel6: run ^point tag 1 ^tag add finishedTag1 ^objective delete mobkillObj5 ^deletepoint mobkillsLevel5 conditions:hasEnoughKills5
   addPoint: run ^point mobkillsLevel 1 ^notify %point.mobkillsLevel.amount% von $mobkillAmount_level0-10$ der Stufe 1 getötet! io:bossbar sound:entity.experience_orb.pickup
   addPoint1: run ^point mobkillsLevel1 1 ^notify %point.mobkillsLevel1.amount% von $mobkillAmount_level0-10$ der Stufe 1 getötet! io:bossbar sound:entity.experience_orb.pickup
   addPoint2: run ^point mobkillsLevel2 1 ^notify %point.mobkillsLevel2.amount% von $mobkillAmount_level10-30$ der Stufe 2 getötet! io:bossbar sound:entity.experience_orb.pickup
   addPoint3: run ^point mobkillsLevel3 1 ^notify %point.mobkillsLevel3.amount% von $mobkillAmount_level30-50$ der Stufe 3 getötet! io:bossbar sound:entity.experience_orb.pickup
   addPoint4: run ^point mobkillsLevel4 1 ^notify %point.mobkillsLevel4.amount% von $mobkillAmount_level50-80$ der Stufe 4 getötet! io:bossbar sound:entity.experience_orb.pickup
   addPoint5: run ^point mobkillsLevel5 1 ^notify %point.mobkillsLevel5.amount% von $mobkillAmount_level80-100$ der Stufe 5 getötet! io:bossbar sound:entity.experience_orb.pickup
   resetQuest: run ^tag del startedTag,finishedTag ^journal delete step_1 ^journal delete step_2 ^journal delete step_3 ^journal delete step_4 ^journal delete step_5 ^journal delete step_6 ^journal update
   rewardPlayer: run ^command mmocore admin exp give %player% $professionName$ $rewardExperienceAmountLevel1$ ^command eco give %player% $rewardCurrencyAmountLevel1$
   finishedLevel3: folder finishedTagDel1And2,deletePointTag,notifyFinishedQuest,finishedTagAdd,journalAdd6 conditions:hasTags
   finishedTagDel1And2: tag del finishedTag1,finishedTag2
   deletePointTag: deletepoint tag
   notifyFinishedQuest: notify &2Quest Fortschritt!\n&6Tagebuch wurde aktualisiert. io:Title sound:entity.player.levelup
   finishedTagAdd: tag add finishedTag
   journalAdd1: run ^journal add step_1 ^journal update
   journalAdd2: run ^journal add step_2 ^journal update
   journalAdd3: run ^journal add step_3 ^journal update
   journalAdd4: run ^journal add step_4 ^journal update
   journalAdd5: run ^journal add step_5 ^journal update
   journalAdd6: run ^journal add step_6 ^journal update
   

conditions:
   startedTag: tag startedTag
   finishedTag: tag finishedTag
   finishedTag1: tag finishedTag1
   finishedTag2: tag finishedTag2
   level10orHigher: mmoprofession $professionName$ 10
   level30orHigher: mmoprofession $professionName$ 30
   level50orHigher: mmoprofession $professionName$ 50
   level80orHigher: mmoprofession $professionName$ 80
   hasEnoughKills: point mobkillsLevel $mobkillAmount_level0-10$
   hasEnoughKills1: point mobkillsLevel1 $mobkillAmount_level0-10$
   hasEnoughKills2: point mobkillsLevel2 $mobkillAmount_level10-30$
   hasEnoughKills3: point mobkillsLevel3 $mobkillAmount_level30-50$
   hasEnoughKills4: point mobkillsLevel4 $mobkillAmount_level50-80$
   hasEnoughKills5: point mobkillsLevel5 $mobkillAmount_level80-100$
   hasTags: point tag 2

objectives:
   mobkillObj: mmobkill $mythicmobsList2$ persistent amount:1 minLevel:1 maxLevel:1 neutralDeathRadiusAllPlayers events:addPoint,finishedLevel
   mobkillObj1: mmobkill $mythicmobsList$ persistent amount:1 minLevel:1 maxLevel:1 neutralDeathRadiusAllPlayers events:addPoint1,finishedLevel1,finishedLevel3
   mobkillObj2: mmobkill $mythicmobsList2$ persistent amount:1 minLevel:1 maxLevel:1 neutralDeathRadiusAllPlayers events:addPoint2,finishedLevel2,finishedLevel3
   mobkillObj3: mmobkill $mythicmobsList$ persistent amount:1 minLevel:1 maxLevel:1 neutralDeathRadiusAllPlayers events:addPoint3,finishedLevel4,finishedLevel3
   mobkillObj4: mmobkill $mythicmobsList2$ persistent amount:1 minLevel:1 maxLevel:1 neutralDeathRadiusAllPlayers events:addPoint4,finishedLevel5,finishedLevel3
   mobkillObj5: mmobkill $mythicmobsList$ persistent amount:1 minLevel:1 maxLevel:1 neutralDeathRadiusAllPlayers events:addPoint5,finishedLevel6,finishedLevel3
   
   

